// Generated by Parametrix
ca_door1arc_faceDoor_000 = [ [ 1500.0000, 1000.0000 ],[ 1900.0000, 1000.0000 ],[ 1884.3155, 1189.2838 ],[ 1489.7710, 1123.4459 ],[ 1500.0000, 1000.0000 ] ];
cb_door1arc_faceDoor_000 = [  0, 1, 2, 3, 4 ];
ca_door1arc_faceDoor_001 = [ [ 1489.7710, 1123.4459 ],[ 1884.3155, 1189.2838 ],[ 1837.6898, 1373.4044 ],[ 1459.3629, 1243.5246 ],[ 1489.7710, 1123.4459 ] ];
cb_door1arc_faceDoor_001 = [  5, 6, 7, 8, 9 ];
ca_door1arc_faceDoor_002 = [ [ 1459.3629, 1243.5246 ],[ 1837.6898, 1373.4044 ],[ 1761.3948, 1547.3395 ],[ 1409.6053, 1356.9605 ],[ 1459.3629, 1243.5246 ] ];
cb_door1arc_faceDoor_002 = [  10, 11, 12, 13, 14 ];
ca_door1arc_faceDoor_003 = [ [ 1409.6053, 1356.9605 ],[ 1761.3948, 1547.3395 ],[ 1657.5116, 1706.3446 ],[ 1341.8554, 1460.6595 ],[ 1409.6053, 1356.9605 ] ];
cb_door1arc_faceDoor_003 = [  15, 16, 17, 18, 19 ];
ca_door1arc_faceDoor_004 = [ [ 1341.8554, 1460.6595 ],[ 1657.5116, 1706.3446 ],[ 1528.8738, 1846.0825 ],[ 1257.9612, 1551.7929 ],[ 1341.8554, 1460.6595 ] ];
cb_door1arc_faceDoor_004 = [  20, 21, 22, 23, 24 ];
ca_door1arc_faceDoor_005 = [ [ 1257.9612, 1551.7929 ],[ 1528.8738, 1846.0825 ],[ 1378.9904, 1962.7415 ],[ 1160.2111, 1627.8749 ],[ 1257.9612, 1551.7929 ] ];
cb_door1arc_faceDoor_005 = [  25, 26, 27, 28, 29 ];
ca_door1arc_faceDoor_006 = [ [ 1160.2111, 1627.8749 ],[ 1378.9904, 1962.7415 ],[ 1211.9497, 2053.1393 ],[ 1051.2716, 1686.8300 ],[ 1160.2111, 1627.8749 ] ];
cb_door1arc_faceDoor_006 = [  30, 31, 32, 33, 34 ];
ca_door1arc_faceDoor_007 = [ [ 1051.2716, 1686.8300 ],[ 1211.9497, 2053.1393 ],[ 1032.3083, 2114.8103 ],[ 934.1141, 1727.0502 ],[ 1051.2716, 1686.8300 ] ];
cb_door1arc_faceDoor_007 = [  35, 36, 37, 38, 39 ];
ca_door1arc_faceDoor_008 = [ [ 934.1141, 1727.0502 ],[ 1032.3083, 2114.8103 ],[ 844.9662, 2146.0722 ],[ 811.9345, 1747.4384 ],[ 934.1141, 1727.0502 ] ];
cb_door1arc_faceDoor_008 = [  40, 41, 42, 43, 44 ];
ca_door1arc_faceDoor_009 = [ [ 811.9345, 1747.4384 ],[ 844.9662, 2146.0722 ],[ 655.0338, 2146.0722 ],[ 688.0655, 1747.4384 ],[ 811.9345, 1747.4384 ] ];
cb_door1arc_faceDoor_009 = [  45, 46, 47, 48, 49 ];
ca_door1arc_faceDoor_010 = [ [ 688.0655, 1747.4384 ],[ 655.0338, 2146.0722 ],[ 467.6917, 2114.8103 ],[ 565.8859, 1727.0502 ],[ 688.0655, 1747.4384 ] ];
cb_door1arc_faceDoor_010 = [  50, 51, 52, 53, 54 ];
ca_door1arc_faceDoor_011 = [ [ 565.8859, 1727.0502 ],[ 467.6917, 2114.8103 ],[ 288.0503, 2053.1393 ],[ 448.7284, 1686.8300 ],[ 565.8859, 1727.0502 ] ];
cb_door1arc_faceDoor_011 = [  55, 56, 57, 58, 59 ];
ca_door1arc_faceDoor_012 = [ [ 448.7284, 1686.8300 ],[ 288.0503, 2053.1393 ],[ 121.0096, 1962.7415 ],[ 339.7889, 1627.8749 ],[ 448.7284, 1686.8300 ] ];
cb_door1arc_faceDoor_012 = [  60, 61, 62, 63, 64 ];
ca_door1arc_faceDoor_013 = [ [ 339.7889, 1627.8749 ],[ 121.0096, 1962.7415 ],[ -28.8738, 1846.0825 ],[ 242.0388, 1551.7929 ],[ 339.7889, 1627.8749 ] ];
cb_door1arc_faceDoor_013 = [  65, 66, 67, 68, 69 ];
ca_door1arc_faceDoor_014 = [ [ 242.0388, 1551.7929 ],[ -28.8738, 1846.0825 ],[ -157.5116, 1706.3446 ],[ 158.1446, 1460.6595 ],[ 242.0388, 1551.7929 ] ];
cb_door1arc_faceDoor_014 = [  70, 71, 72, 73, 74 ];
ca_door1arc_faceDoor_015 = [ [ 158.1446, 1460.6595 ],[ -157.5116, 1706.3446 ],[ -261.3948, 1547.3395 ],[ 90.3947, 1356.9605 ],[ 158.1446, 1460.6595 ] ];
cb_door1arc_faceDoor_015 = [  75, 76, 77, 78, 79 ];
ca_door1arc_faceDoor_016 = [ [ 90.3947, 1356.9605 ],[ -261.3948, 1547.3395 ],[ -337.6898, 1373.4044 ],[ 40.6371, 1243.5246 ],[ 90.3947, 1356.9605 ] ];
cb_door1arc_faceDoor_016 = [  80, 81, 82, 83, 84 ];
ca_door1arc_faceDoor_017 = [ [ 40.6371, 1243.5246 ],[ -337.6898, 1373.4044 ],[ -384.3155, 1189.2838 ],[ 10.2290, 1123.4459 ],[ 40.6371, 1243.5246 ] ];
cb_door1arc_faceDoor_017 = [  85, 86, 87, 88, 89 ];
ca_door1arc_faceDoor_018 = [ [ 10.2290, 1123.4459 ],[ -384.3155, 1189.2838 ],[ -400.0000, 1000.0000 ],[ 0.0000, 1000.0000 ],[ 10.2290, 1123.4459 ] ];
cb_door1arc_faceDoor_018 = [  90, 91, 92, 93, 94 ];
ca_door1arc_faceDoor_019 = [ [ -399.8000, 0.2000 ],[ -0.2000, 0.2000 ],[ -0.2000, 199.8000 ],[ -399.8000, 199.8000 ],[ -399.8000, 0.2000 ] ];
cb_door1arc_faceDoor_019 = [  95, 96, 97, 98, 99 ];
ca_door1arc_faceDoor_020 = [ [ 1500.2000, 0.2000 ],[ 1899.8000, 0.2000 ],[ 1899.8000, 199.8000 ],[ 1500.2000, 199.8000 ],[ 1500.2000, 0.2000 ] ];
cb_door1arc_faceDoor_020 = [  100, 101, 102, 103, 104 ];
ca_door1arc_faceDoor_021 = [ [ -199.8000, 200.2000 ],[ -0.2000, 200.2000 ],[ -0.2000, 399.8000 ],[ -199.8000, 399.8000 ],[ -199.8000, 200.2000 ] ];
cb_door1arc_faceDoor_021 = [  105, 106, 107, 108, 109 ];
ca_door1arc_faceDoor_022 = [ [ 1500.2000, 200.2000 ],[ 1699.8000, 200.2000 ],[ 1699.8000, 399.8000 ],[ 1500.2000, 399.8000 ],[ 1500.2000, 200.2000 ] ];
cb_door1arc_faceDoor_022 = [  110, 111, 112, 113, 114 ];
ca_door1arc_faceDoor_023 = [ [ -399.8000, 400.2000 ],[ -0.2000, 400.2000 ],[ -0.2000, 599.8000 ],[ -399.8000, 599.8000 ],[ -399.8000, 400.2000 ] ];
cb_door1arc_faceDoor_023 = [  115, 116, 117, 118, 119 ];
ca_door1arc_faceDoor_024 = [ [ 1500.2000, 400.2000 ],[ 1899.8000, 400.2000 ],[ 1899.8000, 599.8000 ],[ 1500.2000, 599.8000 ],[ 1500.2000, 400.2000 ] ];
cb_door1arc_faceDoor_024 = [  120, 121, 122, 123, 124 ];
ca_door1arc_faceDoor_025 = [ [ -199.8000, 600.2000 ],[ -0.2000, 600.2000 ],[ -0.2000, 799.8000 ],[ -199.8000, 799.8000 ],[ -199.8000, 600.2000 ] ];
cb_door1arc_faceDoor_025 = [  125, 126, 127, 128, 129 ];
ca_door1arc_faceDoor_026 = [ [ 1500.2000, 600.2000 ],[ 1699.8000, 600.2000 ],[ 1699.8000, 799.8000 ],[ 1500.2000, 799.8000 ],[ 1500.2000, 600.2000 ] ];
cb_door1arc_faceDoor_026 = [  130, 131, 132, 133, 134 ];
ca_door1arc_faceDoor_027 = [ [ -399.8000, 800.2000 ],[ -0.2000, 800.2000 ],[ -0.2000, 999.8000 ],[ -399.8000, 999.8000 ],[ -399.8000, 800.2000 ] ];
cb_door1arc_faceDoor_027 = [  135, 136, 137, 138, 139 ];
ca_door1arc_faceDoor_028 = [ [ 1500.2000, 800.2000 ],[ 1899.8000, 800.2000 ],[ 1899.8000, 999.8000 ],[ 1500.2000, 999.8000 ],[ 1500.2000, 800.2000 ] ];
cb_door1arc_faceDoor_028 = [  140, 141, 142, 143, 144 ];
ca_door1arc_faceDoor_029 = [ [ -199.8000, -199.8000 ],[ 149.8000, -199.8000 ],[ 149.8000, -0.2000 ],[ -199.8000, -0.2000 ],[ -199.8000, -199.8000 ] ];
cb_door1arc_faceDoor_029 = [  145, 146, 147, 148, 149 ];
ca_door1arc_faceDoor_030 = [ [ 150.2000, -199.8000 ],[ 549.8000, -199.8000 ],[ 549.8000, -0.2000 ],[ 150.2000, -0.2000 ],[ 150.2000, -199.8000 ] ];
cb_door1arc_faceDoor_030 = [  150, 151, 152, 153, 154 ];
ca_door1arc_faceDoor_031 = [ [ 550.2000, -199.8000 ],[ 949.8000, -199.8000 ],[ 949.8000, -0.2000 ],[ 550.2000, -0.2000 ],[ 550.2000, -199.8000 ] ];
cb_door1arc_faceDoor_031 = [  155, 156, 157, 158, 159 ];
ca_door1arc_faceDoor_032 = [ [ 950.2000, -199.8000 ],[ 1349.8000, -199.8000 ],[ 1349.8000, -0.2000 ],[ 950.2000, -0.2000 ],[ 950.2000, -199.8000 ] ];
cb_door1arc_faceDoor_032 = [  160, 161, 162, 163, 164 ];
ca_door1arc_faceDoor_033 = [ [ 1350.2000, -199.8000 ],[ 1699.8000, -199.8000 ],[ 1699.8000, -0.2000 ],[ 1350.2000, -0.2000 ],[ 1350.2000, -199.8000 ] ];
cb_door1arc_faceDoor_033 = [  165, 166, 167, 168, 169 ];
a_door1arc_faceDoor = concat(ca_door1arc_faceDoor_000, ca_door1arc_faceDoor_001, ca_door1arc_faceDoor_002, ca_door1arc_faceDoor_003, ca_door1arc_faceDoor_004, ca_door1arc_faceDoor_005, ca_door1arc_faceDoor_006, ca_door1arc_faceDoor_007, ca_door1arc_faceDoor_008, ca_door1arc_faceDoor_009, ca_door1arc_faceDoor_010, ca_door1arc_faceDoor_011, ca_door1arc_faceDoor_012, ca_door1arc_faceDoor_013, ca_door1arc_faceDoor_014, ca_door1arc_faceDoor_015, ca_door1arc_faceDoor_016, ca_door1arc_faceDoor_017, ca_door1arc_faceDoor_018, ca_door1arc_faceDoor_019, ca_door1arc_faceDoor_020, ca_door1arc_faceDoor_021, ca_door1arc_faceDoor_022, ca_door1arc_faceDoor_023, ca_door1arc_faceDoor_024, ca_door1arc_faceDoor_025, ca_door1arc_faceDoor_026, ca_door1arc_faceDoor_027, ca_door1arc_faceDoor_028, ca_door1arc_faceDoor_029, ca_door1arc_faceDoor_030, ca_door1arc_faceDoor_031, ca_door1arc_faceDoor_032, ca_door1arc_faceDoor_033);
b_door1arc_faceDoor = [cb_door1arc_faceDoor_000, cb_door1arc_faceDoor_001, cb_door1arc_faceDoor_002, cb_door1arc_faceDoor_003, cb_door1arc_faceDoor_004, cb_door1arc_faceDoor_005, cb_door1arc_faceDoor_006, cb_door1arc_faceDoor_007, cb_door1arc_faceDoor_008, cb_door1arc_faceDoor_009, cb_door1arc_faceDoor_010, cb_door1arc_faceDoor_011, cb_door1arc_faceDoor_012, cb_door1arc_faceDoor_013, cb_door1arc_faceDoor_014, cb_door1arc_faceDoor_015, cb_door1arc_faceDoor_016, cb_door1arc_faceDoor_017, cb_door1arc_faceDoor_018, cb_door1arc_faceDoor_019, cb_door1arc_faceDoor_020, cb_door1arc_faceDoor_021, cb_door1arc_faceDoor_022, cb_door1arc_faceDoor_023, cb_door1arc_faceDoor_024, cb_door1arc_faceDoor_025, cb_door1arc_faceDoor_026, cb_door1arc_faceDoor_027, cb_door1arc_faceDoor_028, cb_door1arc_faceDoor_029, cb_door1arc_faceDoor_030, cb_door1arc_faceDoor_031, cb_door1arc_faceDoor_032, cb_door1arc_faceDoor_033];

module subpax_door1arc_top () {
	translate( [ 0, 0, 0 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 200) polygon(a_door1arc_faceDoor, b_door1arc_faceDoor);
}

module pax_door1arc () {
	subpax_door1arc_top();
}

pax_door1arc();
