// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_door1arc_faceDoor_Fa000_Ctr000 = polygon({ points: [ [ 1500.0000, 1000.0000 ],
	[ 1900.0000, 1000.0000 ],
	[ 1884.3155, 1189.2838 ],
	[ 1489.7710, 1123.4459 ],
	[ 1500.0000, 1000.0000 ] ] });

face_fig_door1arc_faceDoor_Fa000 = ctr_face_fig_door1arc_faceDoor_Fa000_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa001_Ctr000 = polygon({ points: [ [ 1489.7710, 1123.4459 ],
	[ 1884.3155, 1189.2838 ],
	[ 1837.6898, 1373.4044 ],
	[ 1459.3629, 1243.5246 ],
	[ 1489.7710, 1123.4459 ] ] });

face_fig_door1arc_faceDoor_Fa001 = ctr_face_fig_door1arc_faceDoor_Fa001_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa002_Ctr000 = polygon({ points: [ [ 1459.3629, 1243.5246 ],
	[ 1837.6898, 1373.4044 ],
	[ 1761.3948, 1547.3395 ],
	[ 1409.6053, 1356.9605 ],
	[ 1459.3629, 1243.5246 ] ] });

face_fig_door1arc_faceDoor_Fa002 = ctr_face_fig_door1arc_faceDoor_Fa002_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa003_Ctr000 = polygon({ points: [ [ 1409.6053, 1356.9605 ],
	[ 1761.3948, 1547.3395 ],
	[ 1657.5116, 1706.3446 ],
	[ 1341.8554, 1460.6595 ],
	[ 1409.6053, 1356.9605 ] ] });

face_fig_door1arc_faceDoor_Fa003 = ctr_face_fig_door1arc_faceDoor_Fa003_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa004_Ctr000 = polygon({ points: [ [ 1341.8554, 1460.6595 ],
	[ 1657.5116, 1706.3446 ],
	[ 1528.8738, 1846.0825 ],
	[ 1257.9612, 1551.7929 ],
	[ 1341.8554, 1460.6595 ] ] });

face_fig_door1arc_faceDoor_Fa004 = ctr_face_fig_door1arc_faceDoor_Fa004_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa005_Ctr000 = polygon({ points: [ [ 1257.9612, 1551.7929 ],
	[ 1528.8738, 1846.0825 ],
	[ 1378.9904, 1962.7415 ],
	[ 1160.2111, 1627.8749 ],
	[ 1257.9612, 1551.7929 ] ] });

face_fig_door1arc_faceDoor_Fa005 = ctr_face_fig_door1arc_faceDoor_Fa005_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa006_Ctr000 = polygon({ points: [ [ 1160.2111, 1627.8749 ],
	[ 1378.9904, 1962.7415 ],
	[ 1211.9497, 2053.1393 ],
	[ 1051.2716, 1686.8300 ],
	[ 1160.2111, 1627.8749 ] ] });

face_fig_door1arc_faceDoor_Fa006 = ctr_face_fig_door1arc_faceDoor_Fa006_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa007_Ctr000 = polygon({ points: [ [ 1051.2716, 1686.8300 ],
	[ 1211.9497, 2053.1393 ],
	[ 1032.3083, 2114.8103 ],
	[ 934.1141, 1727.0502 ],
	[ 1051.2716, 1686.8300 ] ] });

face_fig_door1arc_faceDoor_Fa007 = ctr_face_fig_door1arc_faceDoor_Fa007_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa008_Ctr000 = polygon({ points: [ [ 934.1141, 1727.0502 ],
	[ 1032.3083, 2114.8103 ],
	[ 844.9662, 2146.0722 ],
	[ 811.9345, 1747.4384 ],
	[ 934.1141, 1727.0502 ] ] });

face_fig_door1arc_faceDoor_Fa008 = ctr_face_fig_door1arc_faceDoor_Fa008_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa009_Ctr000 = polygon({ points: [ [ 811.9345, 1747.4384 ],
	[ 844.9662, 2146.0722 ],
	[ 655.0338, 2146.0722 ],
	[ 688.0655, 1747.4384 ],
	[ 811.9345, 1747.4384 ] ] });

face_fig_door1arc_faceDoor_Fa009 = ctr_face_fig_door1arc_faceDoor_Fa009_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa010_Ctr000 = polygon({ points: [ [ 688.0655, 1747.4384 ],
	[ 655.0338, 2146.0722 ],
	[ 467.6917, 2114.8103 ],
	[ 565.8859, 1727.0502 ],
	[ 688.0655, 1747.4384 ] ] });

face_fig_door1arc_faceDoor_Fa010 = ctr_face_fig_door1arc_faceDoor_Fa010_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa011_Ctr000 = polygon({ points: [ [ 565.8859, 1727.0502 ],
	[ 467.6917, 2114.8103 ],
	[ 288.0503, 2053.1393 ],
	[ 448.7284, 1686.8300 ],
	[ 565.8859, 1727.0502 ] ] });

face_fig_door1arc_faceDoor_Fa011 = ctr_face_fig_door1arc_faceDoor_Fa011_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa012_Ctr000 = polygon({ points: [ [ 448.7284, 1686.8300 ],
	[ 288.0503, 2053.1393 ],
	[ 121.0096, 1962.7415 ],
	[ 339.7889, 1627.8749 ],
	[ 448.7284, 1686.8300 ] ] });

face_fig_door1arc_faceDoor_Fa012 = ctr_face_fig_door1arc_faceDoor_Fa012_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa013_Ctr000 = polygon({ points: [ [ 339.7889, 1627.8749 ],
	[ 121.0096, 1962.7415 ],
	[ -28.8738, 1846.0825 ],
	[ 242.0388, 1551.7929 ],
	[ 339.7889, 1627.8749 ] ] });

face_fig_door1arc_faceDoor_Fa013 = ctr_face_fig_door1arc_faceDoor_Fa013_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa014_Ctr000 = polygon({ points: [ [ 242.0388, 1551.7929 ],
	[ -28.8738, 1846.0825 ],
	[ -157.5116, 1706.3446 ],
	[ 158.1446, 1460.6595 ],
	[ 242.0388, 1551.7929 ] ] });

face_fig_door1arc_faceDoor_Fa014 = ctr_face_fig_door1arc_faceDoor_Fa014_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa015_Ctr000 = polygon({ points: [ [ 158.1446, 1460.6595 ],
	[ -157.5116, 1706.3446 ],
	[ -261.3948, 1547.3395 ],
	[ 90.3947, 1356.9605 ],
	[ 158.1446, 1460.6595 ] ] });

face_fig_door1arc_faceDoor_Fa015 = ctr_face_fig_door1arc_faceDoor_Fa015_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa016_Ctr000 = polygon({ points: [ [ 90.3947, 1356.9605 ],
	[ -261.3948, 1547.3395 ],
	[ -337.6898, 1373.4044 ],
	[ 40.6371, 1243.5246 ],
	[ 90.3947, 1356.9605 ] ] });

face_fig_door1arc_faceDoor_Fa016 = ctr_face_fig_door1arc_faceDoor_Fa016_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa017_Ctr000 = polygon({ points: [ [ 40.6371, 1243.5246 ],
	[ -337.6898, 1373.4044 ],
	[ -384.3155, 1189.2838 ],
	[ 10.2290, 1123.4459 ],
	[ 40.6371, 1243.5246 ] ] });

face_fig_door1arc_faceDoor_Fa017 = ctr_face_fig_door1arc_faceDoor_Fa017_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa018_Ctr000 = polygon({ points: [ [ 10.2290, 1123.4459 ],
	[ -384.3155, 1189.2838 ],
	[ -400.0000, 1000.0000 ],
	[ 0.0000, 1000.0000 ],
	[ 10.2290, 1123.4459 ] ] });

face_fig_door1arc_faceDoor_Fa018 = ctr_face_fig_door1arc_faceDoor_Fa018_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa019_Ctr000 = polygon({ points: [ [ -399.8000, 0.2000 ],
	[ -0.2000, 0.2000 ],
	[ -0.2000, 199.8000 ],
	[ -399.8000, 199.8000 ],
	[ -399.8000, 0.2000 ] ] });

face_fig_door1arc_faceDoor_Fa019 = ctr_face_fig_door1arc_faceDoor_Fa019_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa020_Ctr000 = polygon({ points: [ [ 1500.2000, 0.2000 ],
	[ 1899.8000, 0.2000 ],
	[ 1899.8000, 199.8000 ],
	[ 1500.2000, 199.8000 ],
	[ 1500.2000, 0.2000 ] ] });

face_fig_door1arc_faceDoor_Fa020 = ctr_face_fig_door1arc_faceDoor_Fa020_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa021_Ctr000 = polygon({ points: [ [ -199.8000, 200.2000 ],
	[ -0.2000, 200.2000 ],
	[ -0.2000, 399.8000 ],
	[ -199.8000, 399.8000 ],
	[ -199.8000, 200.2000 ] ] });

face_fig_door1arc_faceDoor_Fa021 = ctr_face_fig_door1arc_faceDoor_Fa021_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa022_Ctr000 = polygon({ points: [ [ 1500.2000, 200.2000 ],
	[ 1699.8000, 200.2000 ],
	[ 1699.8000, 399.8000 ],
	[ 1500.2000, 399.8000 ],
	[ 1500.2000, 200.2000 ] ] });

face_fig_door1arc_faceDoor_Fa022 = ctr_face_fig_door1arc_faceDoor_Fa022_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa023_Ctr000 = polygon({ points: [ [ -399.8000, 400.2000 ],
	[ -0.2000, 400.2000 ],
	[ -0.2000, 599.8000 ],
	[ -399.8000, 599.8000 ],
	[ -399.8000, 400.2000 ] ] });

face_fig_door1arc_faceDoor_Fa023 = ctr_face_fig_door1arc_faceDoor_Fa023_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa024_Ctr000 = polygon({ points: [ [ 1500.2000, 400.2000 ],
	[ 1899.8000, 400.2000 ],
	[ 1899.8000, 599.8000 ],
	[ 1500.2000, 599.8000 ],
	[ 1500.2000, 400.2000 ] ] });

face_fig_door1arc_faceDoor_Fa024 = ctr_face_fig_door1arc_faceDoor_Fa024_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa025_Ctr000 = polygon({ points: [ [ -199.8000, 600.2000 ],
	[ -0.2000, 600.2000 ],
	[ -0.2000, 799.8000 ],
	[ -199.8000, 799.8000 ],
	[ -199.8000, 600.2000 ] ] });

face_fig_door1arc_faceDoor_Fa025 = ctr_face_fig_door1arc_faceDoor_Fa025_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa026_Ctr000 = polygon({ points: [ [ 1500.2000, 600.2000 ],
	[ 1699.8000, 600.2000 ],
	[ 1699.8000, 799.8000 ],
	[ 1500.2000, 799.8000 ],
	[ 1500.2000, 600.2000 ] ] });

face_fig_door1arc_faceDoor_Fa026 = ctr_face_fig_door1arc_faceDoor_Fa026_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa027_Ctr000 = polygon({ points: [ [ -399.8000, 800.2000 ],
	[ -0.2000, 800.2000 ],
	[ -0.2000, 999.8000 ],
	[ -399.8000, 999.8000 ],
	[ -399.8000, 800.2000 ] ] });

face_fig_door1arc_faceDoor_Fa027 = ctr_face_fig_door1arc_faceDoor_Fa027_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa028_Ctr000 = polygon({ points: [ [ 1500.2000, 800.2000 ],
	[ 1899.8000, 800.2000 ],
	[ 1899.8000, 999.8000 ],
	[ 1500.2000, 999.8000 ],
	[ 1500.2000, 800.2000 ] ] });

face_fig_door1arc_faceDoor_Fa028 = ctr_face_fig_door1arc_faceDoor_Fa028_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa029_Ctr000 = polygon({ points: [ [ -199.8000, -199.8000 ],
	[ 149.8000, -199.8000 ],
	[ 149.8000, -0.2000 ],
	[ -199.8000, -0.2000 ],
	[ -199.8000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa029 = ctr_face_fig_door1arc_faceDoor_Fa029_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa030_Ctr000 = polygon({ points: [ [ 150.2000, -199.8000 ],
	[ 549.8000, -199.8000 ],
	[ 549.8000, -0.2000 ],
	[ 150.2000, -0.2000 ],
	[ 150.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa030 = ctr_face_fig_door1arc_faceDoor_Fa030_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa031_Ctr000 = polygon({ points: [ [ 550.2000, -199.8000 ],
	[ 949.8000, -199.8000 ],
	[ 949.8000, -0.2000 ],
	[ 550.2000, -0.2000 ],
	[ 550.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa031 = ctr_face_fig_door1arc_faceDoor_Fa031_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa032_Ctr000 = polygon({ points: [ [ 950.2000, -199.8000 ],
	[ 1349.8000, -199.8000 ],
	[ 1349.8000, -0.2000 ],
	[ 950.2000, -0.2000 ],
	[ 950.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa032 = ctr_face_fig_door1arc_faceDoor_Fa032_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa033_Ctr000 = polygon({ points: [ [ 1350.2000, -199.8000 ],
	[ 1699.8000, -199.8000 ],
	[ 1699.8000, -0.2000 ],
	[ 1350.2000, -0.2000 ],
	[ 1350.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa033 = ctr_face_fig_door1arc_faceDoor_Fa033_Ctr000;
fig_door1arc_faceDoor = union( face_fig_door1arc_faceDoor_Fa000, face_fig_door1arc_faceDoor_Fa001, face_fig_door1arc_faceDoor_Fa002, face_fig_door1arc_faceDoor_Fa003, face_fig_door1arc_faceDoor_Fa004, face_fig_door1arc_faceDoor_Fa005, face_fig_door1arc_faceDoor_Fa006, face_fig_door1arc_faceDoor_Fa007, face_fig_door1arc_faceDoor_Fa008, face_fig_door1arc_faceDoor_Fa009, face_fig_door1arc_faceDoor_Fa010, face_fig_door1arc_faceDoor_Fa011, face_fig_door1arc_faceDoor_Fa012, face_fig_door1arc_faceDoor_Fa013, face_fig_door1arc_faceDoor_Fa014, face_fig_door1arc_faceDoor_Fa015, face_fig_door1arc_faceDoor_Fa016, face_fig_door1arc_faceDoor_Fa017, face_fig_door1arc_faceDoor_Fa018, face_fig_door1arc_faceDoor_Fa019, face_fig_door1arc_faceDoor_Fa020, face_fig_door1arc_faceDoor_Fa021, face_fig_door1arc_faceDoor_Fa022, face_fig_door1arc_faceDoor_Fa023, face_fig_door1arc_faceDoor_Fa024, face_fig_door1arc_faceDoor_Fa025, face_fig_door1arc_faceDoor_Fa026, face_fig_door1arc_faceDoor_Fa027, face_fig_door1arc_faceDoor_Fa028, face_fig_door1arc_faceDoor_Fa029, face_fig_door1arc_faceDoor_Fa030, face_fig_door1arc_faceDoor_Fa031, face_fig_door1arc_faceDoor_Fa032, face_fig_door1arc_faceDoor_Fa033 );

const subpax_door1arc_top =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 200}, fig_door1arc_faceDoor )
		)
	);

const pax_door1arc = subpax_door1arc_top;

return pax_door1arc;
}
module.exports = { main };
