// Generated by Parametrix
ca_door1arc_faceDoor_000 = [ [ 1500.0000, 1000.0000 ],[ 1820.0000, 1240.0000 ],[ 1695.0327, 1383.9774 ],[ 1412.4061, 1100.9187 ],[ 1500.0000, 1000.0000 ] ];
cb_door1arc_faceDoor_000 = [  0, 1, 2, 3, 4 ];
ca_door1arc_faceDoor_001 = [ [ 1412.4061, 1100.9187 ],[ 1695.0327, 1383.9774 ],[ 1550.8646, 1508.7246 ],[ 1311.3537, 1188.3583 ],[ 1412.4061, 1100.9187 ] ];
cb_door1arc_faceDoor_001 = [  5, 6, 7, 8, 9 ];
ca_door1arc_faceDoor_002 = [ [ 1311.3537, 1188.3583 ],[ 1550.8646, 1508.7246 ],[ 1390.4249, 1611.7070 ],[ 1198.8960, 1260.5423 ],[ 1311.3537, 1188.3583 ] ];
cb_door1arc_faceDoor_002 = [  10, 11, 12, 13, 14 ];
ca_door1arc_faceDoor_003 = [ [ 1198.8960, 1260.5423 ],[ 1390.4249, 1611.7070 ],[ 1216.9733, 1690.8324 ],[ 1077.3177, 1316.0041 ],[ 1198.8960, 1260.5423 ] ];
cb_door1arc_faceDoor_003 = [  15, 16, 17, 18, 19 ];
ca_door1arc_faceDoor_004 = [ [ 1077.3177, 1316.0041 ],[ 1216.9733, 1690.8324 ],[ 1034.0338, 1744.4931 ],[ 949.0891, 1353.6167 ],[ 1077.3177, 1316.0041 ] ];
cb_door1arc_faceDoor_004 = [  20, 21, 22, 23, 24 ];
ca_door1arc_faceDoor_005 = [ [ 949.0891, 1353.6167 ],[ 1034.0338, 1744.4931 ],[ 845.3235, 1771.5988 ],[ 816.8156, 1372.6160 ],[ 949.0891, 1353.6167 ] ];
cb_door1arc_faceDoor_005 = [  25, 26, 27, 28, 29 ];
ca_door1arc_faceDoor_006 = [ [ 816.8156, 1372.6160 ],[ 845.3235, 1771.5988 ],[ 654.6765, 1771.5988 ],[ 683.1844, 1372.6160 ],[ 816.8156, 1372.6160 ] ];
cb_door1arc_faceDoor_006 = [  30, 31, 32, 33, 34 ];
ca_door1arc_faceDoor_007 = [ [ 683.1844, 1372.6160 ],[ 654.6765, 1771.5988 ],[ 465.9662, 1744.4931 ],[ 550.9109, 1353.6167 ],[ 683.1844, 1372.6160 ] ];
cb_door1arc_faceDoor_007 = [  35, 36, 37, 38, 39 ];
ca_door1arc_faceDoor_008 = [ [ 550.9109, 1353.6167 ],[ 465.9662, 1744.4931 ],[ 283.0267, 1690.8324 ],[ 422.6823, 1316.0041 ],[ 550.9109, 1353.6167 ] ];
cb_door1arc_faceDoor_008 = [  40, 41, 42, 43, 44 ];
ca_door1arc_faceDoor_009 = [ [ 422.6823, 1316.0041 ],[ 283.0267, 1690.8324 ],[ 109.5751, 1611.7070 ],[ 301.1040, 1260.5423 ],[ 422.6823, 1316.0041 ] ];
cb_door1arc_faceDoor_009 = [  45, 46, 47, 48, 49 ];
ca_door1arc_faceDoor_010 = [ [ 301.1040, 1260.5423 ],[ 109.5751, 1611.7070 ],[ -50.8646, 1508.7246 ],[ 188.6463, 1188.3583 ],[ 301.1040, 1260.5423 ] ];
cb_door1arc_faceDoor_010 = [  50, 51, 52, 53, 54 ];
ca_door1arc_faceDoor_011 = [ [ 188.6463, 1188.3583 ],[ -50.8646, 1508.7246 ],[ -195.0327, 1383.9774 ],[ 87.5939, 1100.9187 ],[ 188.6463, 1188.3583 ] ];
cb_door1arc_faceDoor_011 = [  55, 56, 57, 58, 59 ];
ca_door1arc_faceDoor_012 = [ [ 87.5939, 1100.9187 ],[ -195.0327, 1383.9774 ],[ -320.0000, 1240.0000 ],[ 0.0000, 1000.0000 ],[ 87.5939, 1100.9187 ] ];
cb_door1arc_faceDoor_012 = [  60, 61, 62, 63, 64 ];
ca_door1arc_faceDoor_013 = [ [ -399.8000, 0.2000 ],[ -0.2000, 0.2000 ],[ -0.2000, 199.8000 ],[ -399.8000, 199.8000 ],[ -399.8000, 0.2000 ] ];
cb_door1arc_faceDoor_013 = [  65, 66, 67, 68, 69 ];
ca_door1arc_faceDoor_014 = [ [ 1500.2000, 0.2000 ],[ 1899.8000, 0.2000 ],[ 1899.8000, 199.8000 ],[ 1500.2000, 199.8000 ],[ 1500.2000, 0.2000 ] ];
cb_door1arc_faceDoor_014 = [  70, 71, 72, 73, 74 ];
ca_door1arc_faceDoor_015 = [ [ -199.8000, 200.2000 ],[ -0.2000, 200.2000 ],[ -0.2000, 399.8000 ],[ -199.8000, 399.8000 ],[ -199.8000, 200.2000 ] ];
cb_door1arc_faceDoor_015 = [  75, 76, 77, 78, 79 ];
ca_door1arc_faceDoor_016 = [ [ 1500.2000, 200.2000 ],[ 1699.8000, 200.2000 ],[ 1699.8000, 399.8000 ],[ 1500.2000, 399.8000 ],[ 1500.2000, 200.2000 ] ];
cb_door1arc_faceDoor_016 = [  80, 81, 82, 83, 84 ];
ca_door1arc_faceDoor_017 = [ [ -399.8000, 400.2000 ],[ -0.2000, 400.2000 ],[ -0.2000, 599.8000 ],[ -399.8000, 599.8000 ],[ -399.8000, 400.2000 ] ];
cb_door1arc_faceDoor_017 = [  85, 86, 87, 88, 89 ];
ca_door1arc_faceDoor_018 = [ [ 1500.2000, 400.2000 ],[ 1899.8000, 400.2000 ],[ 1899.8000, 599.8000 ],[ 1500.2000, 599.8000 ],[ 1500.2000, 400.2000 ] ];
cb_door1arc_faceDoor_018 = [  90, 91, 92, 93, 94 ];
ca_door1arc_faceDoor_019 = [ [ -199.8000, 600.2000 ],[ -0.2000, 600.2000 ],[ -0.2000, 799.8000 ],[ -199.8000, 799.8000 ],[ -199.8000, 600.2000 ] ];
cb_door1arc_faceDoor_019 = [  95, 96, 97, 98, 99 ];
ca_door1arc_faceDoor_020 = [ [ 1500.2000, 600.2000 ],[ 1699.8000, 600.2000 ],[ 1699.8000, 799.8000 ],[ 1500.2000, 799.8000 ],[ 1500.2000, 600.2000 ] ];
cb_door1arc_faceDoor_020 = [  100, 101, 102, 103, 104 ];
ca_door1arc_faceDoor_021 = [ [ -399.8000, 800.2000 ],[ -0.2000, 800.2000 ],[ -0.2000, 999.8000 ],[ -399.8000, 999.8000 ],[ -399.8000, 800.2000 ] ];
cb_door1arc_faceDoor_021 = [  105, 106, 107, 108, 109 ];
ca_door1arc_faceDoor_022 = [ [ 1500.2000, 800.2000 ],[ 1899.8000, 800.2000 ],[ 1899.8000, 999.8000 ],[ 1500.2000, 999.8000 ],[ 1500.2000, 800.2000 ] ];
cb_door1arc_faceDoor_022 = [  110, 111, 112, 113, 114 ];
ca_door1arc_faceDoor_023 = [ [ -199.8000, -199.8000 ],[ 149.8000, -199.8000 ],[ 149.8000, -0.2000 ],[ -199.8000, -0.2000 ],[ -199.8000, -199.8000 ] ];
cb_door1arc_faceDoor_023 = [  115, 116, 117, 118, 119 ];
ca_door1arc_faceDoor_024 = [ [ 150.2000, -199.8000 ],[ 549.8000, -199.8000 ],[ 549.8000, -0.2000 ],[ 150.2000, -0.2000 ],[ 150.2000, -199.8000 ] ];
cb_door1arc_faceDoor_024 = [  120, 121, 122, 123, 124 ];
ca_door1arc_faceDoor_025 = [ [ 550.2000, -199.8000 ],[ 949.8000, -199.8000 ],[ 949.8000, -0.2000 ],[ 550.2000, -0.2000 ],[ 550.2000, -199.8000 ] ];
cb_door1arc_faceDoor_025 = [  125, 126, 127, 128, 129 ];
ca_door1arc_faceDoor_026 = [ [ 950.2000, -199.8000 ],[ 1349.8000, -199.8000 ],[ 1349.8000, -0.2000 ],[ 950.2000, -0.2000 ],[ 950.2000, -199.8000 ] ];
cb_door1arc_faceDoor_026 = [  130, 131, 132, 133, 134 ];
ca_door1arc_faceDoor_027 = [ [ 1350.2000, -199.8000 ],[ 1699.8000, -199.8000 ],[ 1699.8000, -0.2000 ],[ 1350.2000, -0.2000 ],[ 1350.2000, -199.8000 ] ];
cb_door1arc_faceDoor_027 = [  135, 136, 137, 138, 139 ];
ca_door1arc_faceDoor_028 = [ [ 0.0000, 1000.0000 ],[ -266.6667, 1200.0000 ],[ -400.0000, 1200.0000 ],[ -400.0000, 1000.0000 ],[ 0.0000, 1000.0000 ] ];
cb_door1arc_faceDoor_028 = [  140, 141, 142, 143, 144 ];
ca_door1arc_faceDoor_029 = [ [ 1500.0000, 1000.0000 ],[ 1766.6667, 1200.0000 ],[ 1900.0000, 1200.0000 ],[ 1900.0000, 1000.0000 ],[ 1500.0000, 1000.0000 ] ];
cb_door1arc_faceDoor_029 = [  145, 146, 147, 148, 149 ];
a_door1arc_faceDoor = concat(ca_door1arc_faceDoor_000, ca_door1arc_faceDoor_001, ca_door1arc_faceDoor_002, ca_door1arc_faceDoor_003, ca_door1arc_faceDoor_004, ca_door1arc_faceDoor_005, ca_door1arc_faceDoor_006, ca_door1arc_faceDoor_007, ca_door1arc_faceDoor_008, ca_door1arc_faceDoor_009, ca_door1arc_faceDoor_010, ca_door1arc_faceDoor_011, ca_door1arc_faceDoor_012, ca_door1arc_faceDoor_013, ca_door1arc_faceDoor_014, ca_door1arc_faceDoor_015, ca_door1arc_faceDoor_016, ca_door1arc_faceDoor_017, ca_door1arc_faceDoor_018, ca_door1arc_faceDoor_019, ca_door1arc_faceDoor_020, ca_door1arc_faceDoor_021, ca_door1arc_faceDoor_022, ca_door1arc_faceDoor_023, ca_door1arc_faceDoor_024, ca_door1arc_faceDoor_025, ca_door1arc_faceDoor_026, ca_door1arc_faceDoor_027, ca_door1arc_faceDoor_028, ca_door1arc_faceDoor_029);
b_door1arc_faceDoor = [cb_door1arc_faceDoor_000, cb_door1arc_faceDoor_001, cb_door1arc_faceDoor_002, cb_door1arc_faceDoor_003, cb_door1arc_faceDoor_004, cb_door1arc_faceDoor_005, cb_door1arc_faceDoor_006, cb_door1arc_faceDoor_007, cb_door1arc_faceDoor_008, cb_door1arc_faceDoor_009, cb_door1arc_faceDoor_010, cb_door1arc_faceDoor_011, cb_door1arc_faceDoor_012, cb_door1arc_faceDoor_013, cb_door1arc_faceDoor_014, cb_door1arc_faceDoor_015, cb_door1arc_faceDoor_016, cb_door1arc_faceDoor_017, cb_door1arc_faceDoor_018, cb_door1arc_faceDoor_019, cb_door1arc_faceDoor_020, cb_door1arc_faceDoor_021, cb_door1arc_faceDoor_022, cb_door1arc_faceDoor_023, cb_door1arc_faceDoor_024, cb_door1arc_faceDoor_025, cb_door1arc_faceDoor_026, cb_door1arc_faceDoor_027, cb_door1arc_faceDoor_028, cb_door1arc_faceDoor_029];

module subpax_door1arc_top () {
	translate( [ 0, 0, 0 ])
		rotate( [ 0, 0, 0 ])
			   linear_extrude(height = 200) polygon(a_door1arc_faceDoor, b_door1arc_faceDoor);
}

module pax_door1arc () {
	subpax_door1arc_top();
}

pax_door1arc();
