// Generated by Parametrix

const { polygon } = require('@jscad/modeling').primitives;
//const { subtract } = require('@jscad/modeling').booleans;
//const { union, intersect, scission, subtract } = require('@jscad/modeling').booleans;
const { union, intersect, subtract } = require('@jscad/modeling').booleans;
const { extrudeLinear, extrudeRotate } = require('@jscad/modeling').extrusions;
const { translate, rotate } = require('@jscad/modeling').transforms;

const main = () => {

const ctr_face_fig_door1arc_faceDoor_Fa000_Ctr000 = polygon({ points: [ [ 1500.0000, 1000.0000 ],
	[ 1820.0000, 1240.0000 ],
	[ 1695.0327, 1383.9774 ],
	[ 1412.4061, 1100.9187 ],
	[ 1500.0000, 1000.0000 ] ] });

face_fig_door1arc_faceDoor_Fa000 = ctr_face_fig_door1arc_faceDoor_Fa000_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa001_Ctr000 = polygon({ points: [ [ 1412.4061, 1100.9187 ],
	[ 1695.0327, 1383.9774 ],
	[ 1550.8646, 1508.7246 ],
	[ 1311.3537, 1188.3583 ],
	[ 1412.4061, 1100.9187 ] ] });

face_fig_door1arc_faceDoor_Fa001 = ctr_face_fig_door1arc_faceDoor_Fa001_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa002_Ctr000 = polygon({ points: [ [ 1311.3537, 1188.3583 ],
	[ 1550.8646, 1508.7246 ],
	[ 1390.4249, 1611.7070 ],
	[ 1198.8960, 1260.5423 ],
	[ 1311.3537, 1188.3583 ] ] });

face_fig_door1arc_faceDoor_Fa002 = ctr_face_fig_door1arc_faceDoor_Fa002_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa003_Ctr000 = polygon({ points: [ [ 1198.8960, 1260.5423 ],
	[ 1390.4249, 1611.7070 ],
	[ 1216.9733, 1690.8324 ],
	[ 1077.3177, 1316.0041 ],
	[ 1198.8960, 1260.5423 ] ] });

face_fig_door1arc_faceDoor_Fa003 = ctr_face_fig_door1arc_faceDoor_Fa003_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa004_Ctr000 = polygon({ points: [ [ 1077.3177, 1316.0041 ],
	[ 1216.9733, 1690.8324 ],
	[ 1034.0338, 1744.4931 ],
	[ 949.0891, 1353.6167 ],
	[ 1077.3177, 1316.0041 ] ] });

face_fig_door1arc_faceDoor_Fa004 = ctr_face_fig_door1arc_faceDoor_Fa004_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa005_Ctr000 = polygon({ points: [ [ 949.0891, 1353.6167 ],
	[ 1034.0338, 1744.4931 ],
	[ 845.3235, 1771.5988 ],
	[ 816.8156, 1372.6160 ],
	[ 949.0891, 1353.6167 ] ] });

face_fig_door1arc_faceDoor_Fa005 = ctr_face_fig_door1arc_faceDoor_Fa005_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa006_Ctr000 = polygon({ points: [ [ 816.8156, 1372.6160 ],
	[ 845.3235, 1771.5988 ],
	[ 654.6765, 1771.5988 ],
	[ 683.1844, 1372.6160 ],
	[ 816.8156, 1372.6160 ] ] });

face_fig_door1arc_faceDoor_Fa006 = ctr_face_fig_door1arc_faceDoor_Fa006_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa007_Ctr000 = polygon({ points: [ [ 683.1844, 1372.6160 ],
	[ 654.6765, 1771.5988 ],
	[ 465.9662, 1744.4931 ],
	[ 550.9109, 1353.6167 ],
	[ 683.1844, 1372.6160 ] ] });

face_fig_door1arc_faceDoor_Fa007 = ctr_face_fig_door1arc_faceDoor_Fa007_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa008_Ctr000 = polygon({ points: [ [ 550.9109, 1353.6167 ],
	[ 465.9662, 1744.4931 ],
	[ 283.0267, 1690.8324 ],
	[ 422.6823, 1316.0041 ],
	[ 550.9109, 1353.6167 ] ] });

face_fig_door1arc_faceDoor_Fa008 = ctr_face_fig_door1arc_faceDoor_Fa008_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa009_Ctr000 = polygon({ points: [ [ 422.6823, 1316.0041 ],
	[ 283.0267, 1690.8324 ],
	[ 109.5751, 1611.7070 ],
	[ 301.1040, 1260.5423 ],
	[ 422.6823, 1316.0041 ] ] });

face_fig_door1arc_faceDoor_Fa009 = ctr_face_fig_door1arc_faceDoor_Fa009_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa010_Ctr000 = polygon({ points: [ [ 301.1040, 1260.5423 ],
	[ 109.5751, 1611.7070 ],
	[ -50.8646, 1508.7246 ],
	[ 188.6463, 1188.3583 ],
	[ 301.1040, 1260.5423 ] ] });

face_fig_door1arc_faceDoor_Fa010 = ctr_face_fig_door1arc_faceDoor_Fa010_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa011_Ctr000 = polygon({ points: [ [ 188.6463, 1188.3583 ],
	[ -50.8646, 1508.7246 ],
	[ -195.0327, 1383.9774 ],
	[ 87.5939, 1100.9187 ],
	[ 188.6463, 1188.3583 ] ] });

face_fig_door1arc_faceDoor_Fa011 = ctr_face_fig_door1arc_faceDoor_Fa011_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa012_Ctr000 = polygon({ points: [ [ 87.5939, 1100.9187 ],
	[ -195.0327, 1383.9774 ],
	[ -320.0000, 1240.0000 ],
	[ 0.0000, 1000.0000 ],
	[ 87.5939, 1100.9187 ] ] });

face_fig_door1arc_faceDoor_Fa012 = ctr_face_fig_door1arc_faceDoor_Fa012_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa013_Ctr000 = polygon({ points: [ [ -399.8000, 0.2000 ],
	[ -0.2000, 0.2000 ],
	[ -0.2000, 199.8000 ],
	[ -399.8000, 199.8000 ],
	[ -399.8000, 0.2000 ] ] });

face_fig_door1arc_faceDoor_Fa013 = ctr_face_fig_door1arc_faceDoor_Fa013_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa014_Ctr000 = polygon({ points: [ [ 1500.2000, 0.2000 ],
	[ 1899.8000, 0.2000 ],
	[ 1899.8000, 199.8000 ],
	[ 1500.2000, 199.8000 ],
	[ 1500.2000, 0.2000 ] ] });

face_fig_door1arc_faceDoor_Fa014 = ctr_face_fig_door1arc_faceDoor_Fa014_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa015_Ctr000 = polygon({ points: [ [ -199.8000, 200.2000 ],
	[ -0.2000, 200.2000 ],
	[ -0.2000, 399.8000 ],
	[ -199.8000, 399.8000 ],
	[ -199.8000, 200.2000 ] ] });

face_fig_door1arc_faceDoor_Fa015 = ctr_face_fig_door1arc_faceDoor_Fa015_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa016_Ctr000 = polygon({ points: [ [ 1500.2000, 200.2000 ],
	[ 1699.8000, 200.2000 ],
	[ 1699.8000, 399.8000 ],
	[ 1500.2000, 399.8000 ],
	[ 1500.2000, 200.2000 ] ] });

face_fig_door1arc_faceDoor_Fa016 = ctr_face_fig_door1arc_faceDoor_Fa016_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa017_Ctr000 = polygon({ points: [ [ -399.8000, 400.2000 ],
	[ -0.2000, 400.2000 ],
	[ -0.2000, 599.8000 ],
	[ -399.8000, 599.8000 ],
	[ -399.8000, 400.2000 ] ] });

face_fig_door1arc_faceDoor_Fa017 = ctr_face_fig_door1arc_faceDoor_Fa017_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa018_Ctr000 = polygon({ points: [ [ 1500.2000, 400.2000 ],
	[ 1899.8000, 400.2000 ],
	[ 1899.8000, 599.8000 ],
	[ 1500.2000, 599.8000 ],
	[ 1500.2000, 400.2000 ] ] });

face_fig_door1arc_faceDoor_Fa018 = ctr_face_fig_door1arc_faceDoor_Fa018_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa019_Ctr000 = polygon({ points: [ [ -199.8000, 600.2000 ],
	[ -0.2000, 600.2000 ],
	[ -0.2000, 799.8000 ],
	[ -199.8000, 799.8000 ],
	[ -199.8000, 600.2000 ] ] });

face_fig_door1arc_faceDoor_Fa019 = ctr_face_fig_door1arc_faceDoor_Fa019_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa020_Ctr000 = polygon({ points: [ [ 1500.2000, 600.2000 ],
	[ 1699.8000, 600.2000 ],
	[ 1699.8000, 799.8000 ],
	[ 1500.2000, 799.8000 ],
	[ 1500.2000, 600.2000 ] ] });

face_fig_door1arc_faceDoor_Fa020 = ctr_face_fig_door1arc_faceDoor_Fa020_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa021_Ctr000 = polygon({ points: [ [ -399.8000, 800.2000 ],
	[ -0.2000, 800.2000 ],
	[ -0.2000, 999.8000 ],
	[ -399.8000, 999.8000 ],
	[ -399.8000, 800.2000 ] ] });

face_fig_door1arc_faceDoor_Fa021 = ctr_face_fig_door1arc_faceDoor_Fa021_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa022_Ctr000 = polygon({ points: [ [ 1500.2000, 800.2000 ],
	[ 1899.8000, 800.2000 ],
	[ 1899.8000, 999.8000 ],
	[ 1500.2000, 999.8000 ],
	[ 1500.2000, 800.2000 ] ] });

face_fig_door1arc_faceDoor_Fa022 = ctr_face_fig_door1arc_faceDoor_Fa022_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa023_Ctr000 = polygon({ points: [ [ -199.8000, -199.8000 ],
	[ 149.8000, -199.8000 ],
	[ 149.8000, -0.2000 ],
	[ -199.8000, -0.2000 ],
	[ -199.8000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa023 = ctr_face_fig_door1arc_faceDoor_Fa023_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa024_Ctr000 = polygon({ points: [ [ 150.2000, -199.8000 ],
	[ 549.8000, -199.8000 ],
	[ 549.8000, -0.2000 ],
	[ 150.2000, -0.2000 ],
	[ 150.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa024 = ctr_face_fig_door1arc_faceDoor_Fa024_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa025_Ctr000 = polygon({ points: [ [ 550.2000, -199.8000 ],
	[ 949.8000, -199.8000 ],
	[ 949.8000, -0.2000 ],
	[ 550.2000, -0.2000 ],
	[ 550.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa025 = ctr_face_fig_door1arc_faceDoor_Fa025_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa026_Ctr000 = polygon({ points: [ [ 950.2000, -199.8000 ],
	[ 1349.8000, -199.8000 ],
	[ 1349.8000, -0.2000 ],
	[ 950.2000, -0.2000 ],
	[ 950.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa026 = ctr_face_fig_door1arc_faceDoor_Fa026_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa027_Ctr000 = polygon({ points: [ [ 1350.2000, -199.8000 ],
	[ 1699.8000, -199.8000 ],
	[ 1699.8000, -0.2000 ],
	[ 1350.2000, -0.2000 ],
	[ 1350.2000, -199.8000 ] ] });

face_fig_door1arc_faceDoor_Fa027 = ctr_face_fig_door1arc_faceDoor_Fa027_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa028_Ctr000 = polygon({ points: [ [ 0.0000, 1000.0000 ],
	[ -266.6667, 1200.0000 ],
	[ -400.0000, 1200.0000 ],
	[ -400.0000, 1000.0000 ],
	[ 0.0000, 1000.0000 ] ] });

face_fig_door1arc_faceDoor_Fa028 = ctr_face_fig_door1arc_faceDoor_Fa028_Ctr000;
const ctr_face_fig_door1arc_faceDoor_Fa029_Ctr000 = polygon({ points: [ [ 1500.0000, 1000.0000 ],
	[ 1766.6667, 1200.0000 ],
	[ 1900.0000, 1200.0000 ],
	[ 1900.0000, 1000.0000 ],
	[ 1500.0000, 1000.0000 ] ] });

face_fig_door1arc_faceDoor_Fa029 = ctr_face_fig_door1arc_faceDoor_Fa029_Ctr000;
fig_door1arc_faceDoor = union( face_fig_door1arc_faceDoor_Fa000, face_fig_door1arc_faceDoor_Fa001, face_fig_door1arc_faceDoor_Fa002, face_fig_door1arc_faceDoor_Fa003, face_fig_door1arc_faceDoor_Fa004, face_fig_door1arc_faceDoor_Fa005, face_fig_door1arc_faceDoor_Fa006, face_fig_door1arc_faceDoor_Fa007, face_fig_door1arc_faceDoor_Fa008, face_fig_door1arc_faceDoor_Fa009, face_fig_door1arc_faceDoor_Fa010, face_fig_door1arc_faceDoor_Fa011, face_fig_door1arc_faceDoor_Fa012, face_fig_door1arc_faceDoor_Fa013, face_fig_door1arc_faceDoor_Fa014, face_fig_door1arc_faceDoor_Fa015, face_fig_door1arc_faceDoor_Fa016, face_fig_door1arc_faceDoor_Fa017, face_fig_door1arc_faceDoor_Fa018, face_fig_door1arc_faceDoor_Fa019, face_fig_door1arc_faceDoor_Fa020, face_fig_door1arc_faceDoor_Fa021, face_fig_door1arc_faceDoor_Fa022, face_fig_door1arc_faceDoor_Fa023, face_fig_door1arc_faceDoor_Fa024, face_fig_door1arc_faceDoor_Fa025, face_fig_door1arc_faceDoor_Fa026, face_fig_door1arc_faceDoor_Fa027, face_fig_door1arc_faceDoor_Fa028, face_fig_door1arc_faceDoor_Fa029 );

const subpax_door1arc_top =
	translate( [ 0, 0, 0, ],
		rotate( [ 0, 0, 0, ],
			   extrudeLinear( {height: 200}, fig_door1arc_faceDoor )
		)
	);

const pax_door1arc = subpax_door1arc_top;

return pax_door1arc;
}
module.exports = { main };
