# freecad-python generated by Parametrix
# run the script with:
# freecad.cmd myScript.py

import FreeCAD as App
import Part

#print(sys.argv)
outFileName = "rccar"
if (len(sys.argv) == 3):
    outFileName = sys.argv[2]
print(f"outFileName: {outFileName}")

def ctr_face_rccar_facePlatform_Fa0_Ctr0():
	P000 = App.Vector(-50.0000, 0.0000, 0)
	P001 = App.Vector(50.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(50.0000, 220.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(600.0000, 220.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(600.0000, 230.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-600.0000, 230.0000, 0)
	S004 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-600.0000, 220.0000, 0)
	S005 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-50.0000, 220.0000, 0)
	S006 = Part.LineSegment(P006, P007)
	P008 = App.Vector(-50.0000, 0.0000, 0)
	S007 = Part.LineSegment(P007, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_facePlatform_Fa0_Ctr1():
	P000 = App.Vector(-40.0000, 10.0000, 0)
	P001 = App.Vector(40.0000, 10.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 220.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 220.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 10.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_facePlatform_Fa0():
	FC000 = ctr_face_rccar_facePlatform_Fa0_Ctr0()
	FC001 = ctr_face_rccar_facePlatform_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_facePlatform():
	FA000 = face_rccar_facePlatform_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceTop_Fa0_Ctr0():
	P000 = App.Vector(-600.0000, 0.0000, 0)
	P001 = App.Vector(600.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(600.0000, 1250.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-600.0000, 1250.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-600.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceTop_Fa0_Ctr1():
	P000 = App.Vector(-40.0000, 0.0000, 0)
	P001 = App.Vector(40.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(40.0000, 1250.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-40.0000, 1250.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-40.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceTop_Fa0():
	FC000 = ctr_face_rccar_faceTop_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceTop_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_faceTop():
	FA000 = face_rccar_faceTop_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceSide_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(1250.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(1250.0000, 230.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(0.0000, 230.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(0.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceSide_Fa0():
	FC000 = ctr_face_rccar_faceSide_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rccar_faceSide():
	FA000 = face_rccar_faceSide_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceTriangle_Fa0_Ctr0():
	P000 = App.Vector(-50.0000, 0.0000, 0)
	P001 = App.Vector(-40.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-40.0000, 230.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-600.0000, 230.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-600.0000, 220.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-50.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceTriangle_Fa0():
	FC000 = ctr_face_rccar_faceTriangle_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceTriangle_Fa1_Ctr0():
	P000 = App.Vector(50.0000, 0.0000, 0)
	P001 = App.Vector(600.0000, 220.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(600.0000, 230.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(40.0000, 230.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(40.0000, 0.0000, 0)
	S003 = Part.LineSegment(P003, P004)
	P005 = App.Vector(50.0000, 0.0000, 0)
	S004 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceTriangle_Fa1():
	FC000 = ctr_face_rccar_faceTriangle_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rccar_faceTriangle():
	FA000 = face_rccar_faceTriangle_Fa0()
	FA001 = face_rccar_faceTriangle_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_facePFfixation_Fa0_Ctr0():
	P000 = App.Vector(40.0000, 0.0000, 0)
	P001 = App.Vector(80.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(100.0000, 20.0000, 0)
	P003 = App.Vector(80.0000, 40.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(50.0000, 40.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(50.0000, 120.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(80.0000, 120.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(100.0000, 140.0000, 0)
	P008 = App.Vector(80.0000, 160.0000, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(40.0000, 160.0000, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(40.0000, 0.0000, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_facePFfixation_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(80.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_facePFfixation_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(80.0000, 140.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_facePFfixation_Fa0():
	FC000 = ctr_face_rccar_facePFfixation_Fa0_Ctr0()
	FC001 = ctr_face_rccar_facePFfixation_Fa0_Ctr1()
	FC002 = ctr_face_rccar_facePFfixation_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_facePFfixation_Fa1_Ctr0():
	P000 = App.Vector(-40.0000, 0.0000, 0)
	P001 = App.Vector(-80.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-100.0000, 20.0000, 0)
	P003 = App.Vector(-80.0000, 40.0000, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-50.0000, 40.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-50.0000, 120.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-80.0000, 120.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-100.0000, 140.0000, 0)
	P008 = App.Vector(-80.0000, 160.0000, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(-40.0000, 160.0000, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-40.0000, 0.0000, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_facePFfixation_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-80.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_facePFfixation_Fa1_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-80.0000, 140.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_facePFfixation_Fa1():
	FC000 = ctr_face_rccar_facePFfixation_Fa1_Ctr0()
	FC001 = ctr_face_rccar_facePFfixation_Fa1_Ctr1()
	FC002 = ctr_face_rccar_facePFfixation_Fa1_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def rccar_facePFfixation():
	FA000 = face_rccar_facePFfixation_Fa0()
	FA001 = face_rccar_facePFfixation_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceBones_Fa0_Ctr0():
	P000 = App.Vector(99.7756, 22.9874, 0)
	P001 = App.Vector(64.6791, 32.8558, 0)
	P002 = App.Vector(80.4920, 0.0061, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(175.1310, -79.4055, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(210.2276, -89.2739, 0)
	P005 = App.Vector(194.4147, -56.4242, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(99.7756, 22.9874, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceBones_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(80.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_faceBones_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(194.9067, -76.4181, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceBones_Fa0():
	FC000 = ctr_face_rccar_faceBones_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceBones_Fa0_Ctr1()
	FC002 = ctr_face_rccar_faceBones_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceBones_Fa1_Ctr0():
	P000 = App.Vector(99.7756, 142.9874, 0)
	P001 = App.Vector(64.6791, 152.8558, 0)
	P002 = App.Vector(80.4920, 120.0061, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(175.1310, 40.5945, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(210.2276, 30.7261, 0)
	P005 = App.Vector(194.4147, 63.5758, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(99.7756, 142.9874, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceBones_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(80.0000, 140.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_faceBones_Fa1_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(194.9067, 43.5819, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceBones_Fa1():
	FC000 = ctr_face_rccar_faceBones_Fa1_Ctr0()
	FC001 = ctr_face_rccar_faceBones_Fa1_Ctr1()
	FC002 = ctr_face_rccar_faceBones_Fa1_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceBones_Fa2_Ctr0():
	P000 = App.Vector(-80.4920, 0.0061, 0)
	P001 = App.Vector(-64.6791, 32.8558, 0)
	P002 = App.Vector(-99.7756, 22.9874, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-194.4147, -56.4242, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-210.2276, -89.2739, 0)
	P005 = App.Vector(-175.1310, -79.4055, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-80.4920, 0.0061, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceBones_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-80.0000, 20.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_faceBones_Fa2_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-194.9067, -76.4181, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceBones_Fa2():
	FC000 = ctr_face_rccar_faceBones_Fa2_Ctr0()
	FC001 = ctr_face_rccar_faceBones_Fa2_Ctr1()
	FC002 = ctr_face_rccar_faceBones_Fa2_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceBones_Fa3_Ctr0():
	P000 = App.Vector(-80.4920, 120.0061, 0)
	P001 = App.Vector(-64.6791, 152.8558, 0)
	P002 = App.Vector(-99.7756, 142.9874, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-194.4147, 63.5758, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-210.2276, 30.7261, 0)
	P005 = App.Vector(-175.1310, 40.5945, 0)
	S002 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(-80.4920, 120.0061, 0)
	S003 = Part.LineSegment(P005, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceBones_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-80.0000, 140.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_faceBones_Fa3_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-194.9067, 43.5819, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceBones_Fa3():
	FC000 = ctr_face_rccar_faceBones_Fa3_Ctr0()
	FC001 = ctr_face_rccar_faceBones_Fa3_Ctr1()
	FC002 = ctr_face_rccar_faceBones_Fa3_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def rccar_faceBones():
	FA000 = face_rccar_faceBones_Fa0()
	FA001 = face_rccar_faceBones_Fa1()
	FA002 = face_rccar_faceBones_Fa2()
	FA003 = face_rccar_faceBones_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceHandFixation_Fa0_Ctr0():
	P000 = App.Vector(234.9067, -96.4181, 0)
	P001 = App.Vector(194.9067, -96.4181, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(174.9067, -76.4181, 0)
	P003 = App.Vector(194.9067, -56.4181, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(224.9067, -56.4181, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(224.9067, 23.5819, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(194.9067, 23.5819, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(174.9067, 43.5819, 0)
	P008 = App.Vector(194.9067, 63.5819, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(234.9067, 63.5819, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(234.9067, -96.4181, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandFixation_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(194.9067, -76.4181, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_faceHandFixation_Fa0_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(194.9067, 43.5819, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandFixation_Fa0():
	FC000 = ctr_face_rccar_faceHandFixation_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceHandFixation_Fa0_Ctr1()
	FC002 = ctr_face_rccar_faceHandFixation_Fa0_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandFixation_Fa1_Ctr0():
	P000 = App.Vector(-234.9067, -96.4181, 0)
	P001 = App.Vector(-194.9067, -96.4181, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-174.9067, -76.4181, 0)
	P003 = App.Vector(-194.9067, -56.4181, 0)
	S001 = Part.Arc(P001, P002, P003)
	P004 = App.Vector(-224.9067, -56.4181, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-224.9067, 23.5819, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-194.9067, 23.5819, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-174.9067, 43.5819, 0)
	P008 = App.Vector(-194.9067, 63.5819, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(-234.9067, 63.5819, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(-234.9067, -96.4181, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandFixation_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-194.9067, -76.4181, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def ctr_face_rccar_faceHandFixation_Fa1_Ctr2():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(10.0000, App.Vector(-194.9067, 43.5819, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandFixation_Fa1():
	FC000 = ctr_face_rccar_faceHandFixation_Fa1_Ctr0()
	FC001 = ctr_face_rccar_faceHandFixation_Fa1_Ctr1()
	FC002 = ctr_face_rccar_faceHandFixation_Fa1_Ctr2()
	rOneFace = FC000.cut([FC001, FC002])
	rOneFace.check()
	return rOneFace

def rccar_faceHandFixation():
	FA000 = face_rccar_faceHandFixation_Fa0()
	FA001 = face_rccar_faceHandFixation_Fa1()
	rOneFig = FA000.fuse([FA001])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceHandPlateR_Fa0_Ctr0():
	P000 = App.Vector(334.9067, 70.0000, 0)
	P001 = App.Vector(424.9067, 160.0000, 0)
	P002 = App.Vector(334.9067, 250.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(224.9067, 250.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 70.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 70.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateR_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 160.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateR_Fa0():
	FC000 = ctr_face_rccar_faceHandPlateR_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateR_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandPlateR_Fa1_Ctr0():
	P000 = App.Vector(334.9067, 380.0000, 0)
	P001 = App.Vector(424.9067, 470.0000, 0)
	P002 = App.Vector(334.9067, 560.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(224.9067, 560.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 380.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 380.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateR_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 470.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateR_Fa1():
	FC000 = ctr_face_rccar_faceHandPlateR_Fa1_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateR_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandPlateR_Fa2_Ctr0():
	P000 = App.Vector(334.9067, 690.0000, 0)
	P001 = App.Vector(424.9067, 780.0000, 0)
	P002 = App.Vector(334.9067, 870.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(224.9067, 870.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 690.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 690.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateR_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 780.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateR_Fa2():
	FC000 = ctr_face_rccar_faceHandPlateR_Fa2_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateR_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandPlateR_Fa3_Ctr0():
	P000 = App.Vector(334.9067, 1000.0000, 0)
	P001 = App.Vector(424.9067, 1090.0000, 0)
	P002 = App.Vector(334.9067, 1180.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(224.9067, 1180.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 1000.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 1000.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateR_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 1090.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateR_Fa3():
	FC000 = ctr_face_rccar_faceHandPlateR_Fa3_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateR_Fa3_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_faceHandPlateR():
	FA000 = face_rccar_faceHandPlateR_Fa0()
	FA001 = face_rccar_faceHandPlateR_Fa1()
	FA002 = face_rccar_faceHandPlateR_Fa2()
	FA003 = face_rccar_faceHandPlateR_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceHandPlateL_Fa0_Ctr0():
	P000 = App.Vector(-334.9067, 250.0000, 0)
	P001 = App.Vector(-424.9067, 160.0000, 0)
	P002 = App.Vector(-334.9067, 70.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-224.9067, 70.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-224.9067, 250.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 250.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateL_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 160.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateL_Fa0():
	FC000 = ctr_face_rccar_faceHandPlateL_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateL_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandPlateL_Fa1_Ctr0():
	P000 = App.Vector(-334.9067, 560.0000, 0)
	P001 = App.Vector(-424.9067, 470.0000, 0)
	P002 = App.Vector(-334.9067, 380.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-224.9067, 380.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-224.9067, 560.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 560.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateL_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 470.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateL_Fa1():
	FC000 = ctr_face_rccar_faceHandPlateL_Fa1_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateL_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandPlateL_Fa2_Ctr0():
	P000 = App.Vector(-334.9067, 870.0000, 0)
	P001 = App.Vector(-424.9067, 780.0000, 0)
	P002 = App.Vector(-334.9067, 690.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-224.9067, 690.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-224.9067, 870.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 870.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateL_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 780.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateL_Fa2():
	FC000 = ctr_face_rccar_faceHandPlateL_Fa2_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateL_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandPlateL_Fa3_Ctr0():
	P000 = App.Vector(-334.9067, 1180.0000, 0)
	P001 = App.Vector(-424.9067, 1090.0000, 0)
	P002 = App.Vector(-334.9067, 1000.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-224.9067, 1000.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-224.9067, 1180.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 1180.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceHandPlateL_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 1090.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceHandPlateL_Fa3():
	FC000 = ctr_face_rccar_faceHandPlateL_Fa3_Ctr0()
	FC001 = ctr_face_rccar_faceHandPlateL_Fa3_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_faceHandPlateL():
	FA000 = face_rccar_faceHandPlateL_Fa0()
	FA001 = face_rccar_faceHandPlateL_Fa1()
	FA002 = face_rccar_faceHandPlateL_Fa2()
	FA003 = face_rccar_faceHandPlateL_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceHandBackR_Fa0_Ctr0():
	P000 = App.Vector(224.9067, 70.0000, 0)
	P001 = App.Vector(234.9067, 70.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(234.9067, 250.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(224.9067, 250.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 70.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackR_Fa0():
	FC000 = ctr_face_rccar_faceHandBackR_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandBackR_Fa1_Ctr0():
	P000 = App.Vector(224.9067, 380.0000, 0)
	P001 = App.Vector(234.9067, 380.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(234.9067, 560.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(224.9067, 560.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 380.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackR_Fa1():
	FC000 = ctr_face_rccar_faceHandBackR_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandBackR_Fa2_Ctr0():
	P000 = App.Vector(224.9067, 690.0000, 0)
	P001 = App.Vector(234.9067, 690.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(234.9067, 870.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(224.9067, 870.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 690.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackR_Fa2():
	FC000 = ctr_face_rccar_faceHandBackR_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandBackR_Fa3_Ctr0():
	P000 = App.Vector(224.9067, 1000.0000, 0)
	P001 = App.Vector(234.9067, 1000.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(234.9067, 1180.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(224.9067, 1180.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(224.9067, 1000.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackR_Fa3():
	FC000 = ctr_face_rccar_faceHandBackR_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rccar_faceHandBackR():
	FA000 = face_rccar_faceHandBackR_Fa0()
	FA001 = face_rccar_faceHandBackR_Fa1()
	FA002 = face_rccar_faceHandBackR_Fa2()
	FA003 = face_rccar_faceHandBackR_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceHandBackL_Fa0_Ctr0():
	P000 = App.Vector(-234.9067, 70.0000, 0)
	P001 = App.Vector(-224.9067, 70.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-224.9067, 250.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-234.9067, 250.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-234.9067, 70.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackL_Fa0():
	FC000 = ctr_face_rccar_faceHandBackL_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandBackL_Fa1_Ctr0():
	P000 = App.Vector(-234.9067, 380.0000, 0)
	P001 = App.Vector(-224.9067, 380.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-224.9067, 560.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-234.9067, 560.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-234.9067, 380.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackL_Fa1():
	FC000 = ctr_face_rccar_faceHandBackL_Fa1_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandBackL_Fa2_Ctr0():
	P000 = App.Vector(-234.9067, 690.0000, 0)
	P001 = App.Vector(-224.9067, 690.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-224.9067, 870.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-234.9067, 870.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-234.9067, 690.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackL_Fa2():
	FC000 = ctr_face_rccar_faceHandBackL_Fa2_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceHandBackL_Fa3_Ctr0():
	P000 = App.Vector(-234.9067, 1000.0000, 0)
	P001 = App.Vector(-224.9067, 1000.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(-224.9067, 1180.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(-234.9067, 1180.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-234.9067, 1000.0000, 0)
	S003 = Part.LineSegment(P003, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceHandBackL_Fa3():
	FC000 = ctr_face_rccar_faceHandBackL_Fa3_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rccar_faceHandBackL():
	FA000 = face_rccar_faceHandBackL_Fa0()
	FA001 = face_rccar_faceHandBackL_Fa1()
	FA002 = face_rccar_faceHandBackL_Fa2()
	FA003 = face_rccar_faceHandBackL_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceMotorBulkR_Fa0_Ctr0():
	P000 = App.Vector(334.9067, 250.0000, 0)
	P001 = App.Vector(244.9067, 160.0000, 0)
	P002 = App.Vector(334.9067, 70.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(474.9067, 70.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(474.9067, 250.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 250.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkR_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 160.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkR_Fa0():
	FC000 = ctr_face_rccar_faceMotorBulkR_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkR_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceMotorBulkR_Fa1_Ctr0():
	P000 = App.Vector(334.9067, 560.0000, 0)
	P001 = App.Vector(244.9067, 470.0000, 0)
	P002 = App.Vector(334.9067, 380.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(474.9067, 380.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(474.9067, 560.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 560.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkR_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 470.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkR_Fa1():
	FC000 = ctr_face_rccar_faceMotorBulkR_Fa1_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkR_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceMotorBulkR_Fa2_Ctr0():
	P000 = App.Vector(334.9067, 870.0000, 0)
	P001 = App.Vector(244.9067, 780.0000, 0)
	P002 = App.Vector(334.9067, 690.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(474.9067, 690.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(474.9067, 870.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 870.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkR_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 780.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkR_Fa2():
	FC000 = ctr_face_rccar_faceMotorBulkR_Fa2_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkR_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceMotorBulkR_Fa3_Ctr0():
	P000 = App.Vector(334.9067, 1180.0000, 0)
	P001 = App.Vector(244.9067, 1090.0000, 0)
	P002 = App.Vector(334.9067, 1000.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(474.9067, 1000.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(474.9067, 1180.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(334.9067, 1180.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkR_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(334.9067, 1090.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkR_Fa3():
	FC000 = ctr_face_rccar_faceMotorBulkR_Fa3_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkR_Fa3_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_faceMotorBulkR():
	FA000 = face_rccar_faceMotorBulkR_Fa0()
	FA001 = face_rccar_faceMotorBulkR_Fa1()
	FA002 = face_rccar_faceMotorBulkR_Fa2()
	FA003 = face_rccar_faceMotorBulkR_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceMotorBulkL_Fa0_Ctr0():
	P000 = App.Vector(-334.9067, 70.0000, 0)
	P001 = App.Vector(-244.9067, 160.0000, 0)
	P002 = App.Vector(-334.9067, 250.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-474.9067, 250.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-474.9067, 70.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 70.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkL_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 160.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkL_Fa0():
	FC000 = ctr_face_rccar_faceMotorBulkL_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkL_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceMotorBulkL_Fa1_Ctr0():
	P000 = App.Vector(-334.9067, 380.0000, 0)
	P001 = App.Vector(-244.9067, 470.0000, 0)
	P002 = App.Vector(-334.9067, 560.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-474.9067, 560.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-474.9067, 380.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 380.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkL_Fa1_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 470.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkL_Fa1():
	FC000 = ctr_face_rccar_faceMotorBulkL_Fa1_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkL_Fa1_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceMotorBulkL_Fa2_Ctr0():
	P000 = App.Vector(-334.9067, 690.0000, 0)
	P001 = App.Vector(-244.9067, 780.0000, 0)
	P002 = App.Vector(-334.9067, 870.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-474.9067, 870.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-474.9067, 690.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 690.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkL_Fa2_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 780.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkL_Fa2():
	FC000 = ctr_face_rccar_faceMotorBulkL_Fa2_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkL_Fa2_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def ctr_face_rccar_faceMotorBulkL_Fa3_Ctr0():
	P000 = App.Vector(-334.9067, 1000.0000, 0)
	P001 = App.Vector(-244.9067, 1090.0000, 0)
	P002 = App.Vector(-334.9067, 1180.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(-474.9067, 1180.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(-474.9067, 1000.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-334.9067, 1000.0000, 0)
	S003 = Part.LineSegment(P004, P000)
	aShape = Part.Shape([S000, S001, S002, S003])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMotorBulkL_Fa3_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(-334.9067, 1090.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMotorBulkL_Fa3():
	FC000 = ctr_face_rccar_faceMotorBulkL_Fa3_Ctr0()
	FC001 = ctr_face_rccar_faceMotorBulkL_Fa3_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_faceMotorBulkL():
	FA000 = face_rccar_faceMotorBulkL_Fa0()
	FA001 = face_rccar_faceMotorBulkL_Fa1()
	FA002 = face_rccar_faceMotorBulkL_Fa2()
	FA003 = face_rccar_faceMotorBulkL_Fa3()
	rOneFig = FA000.fuse([FA001, FA002, FA003])
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceMFoot_Fa0_Ctr0():
	P000 = App.Vector(-30.0000, 0.0000, 0)
	P001 = App.Vector(-0.0000, -30.0000, 0)
	P002 = App.Vector(30.0000, 0.0000, 0)
	S000 = Part.Arc(P000, P001, P002)
	P003 = App.Vector(90.0000, 120.0000, 0)
	S001 = Part.LineSegment(P002, P003)
	P004 = App.Vector(90.0000, 240.0000, 0)
	S002 = Part.LineSegment(P003, P004)
	P005 = App.Vector(-90.0000, 240.0000, 0)
	S003 = Part.LineSegment(P004, P005)
	P006 = App.Vector(-90.0000, 120.0000, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(-30.0000, 0.0000, 0)
	S005 = Part.LineSegment(P006, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def ctr_face_rccar_faceMFoot_Fa0_Ctr1():
	# Radius, XYZ-position, orientation
	aCircle = Part.makeCircle(20.0000, App.Vector(0.0000, 0.0000, 0), App.Vector(0, 0, 1))
	aWire = Part.Wire(aCircle)
	rFace = Part.Face(aWire)
	return rFace

def face_rccar_faceMFoot_Fa0():
	FC000 = ctr_face_rccar_faceMFoot_Fa0_Ctr0()
	FC001 = ctr_face_rccar_faceMFoot_Fa0_Ctr1()
	rOneFace = FC000.cut([FC001])
	rOneFace.check()
	return rOneFace

def rccar_faceMFoot():
	FA000 = face_rccar_faceMFoot_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def ctr_face_rccar_faceWheel_Fa0_Ctr0():
	P000 = App.Vector(0.0000, 0.0000, 0)
	P001 = App.Vector(10.0000, 0.0000, 0)
	S000 = Part.LineSegment(P000, P001)
	P002 = App.Vector(10.0000, 70.0000, 0)
	S001 = Part.LineSegment(P001, P002)
	P003 = App.Vector(91.6667, 70.0000, 0)
	S002 = Part.LineSegment(P002, P003)
	P004 = App.Vector(115.2369, 79.7631, 0)
	P005 = App.Vector(125.0000, 103.3333, 0)
	S003 = Part.Arc(P003, P004, P005)
	P006 = App.Vector(125.0000, 136.6667, 0)
	S004 = Part.LineSegment(P005, P006)
	P007 = App.Vector(115.2369, 160.2369, 0)
	P008 = App.Vector(91.6667, 170.0000, 0)
	S005 = Part.Arc(P006, P007, P008)
	P009 = App.Vector(0.0000, 170.0000, 0)
	S006 = Part.LineSegment(P008, P009)
	P010 = App.Vector(0.0000, 0.0000, 0)
	S007 = Part.LineSegment(P009, P000)
	aShape = Part.Shape([S000, S001, S002, S003, S004, S005, S006, S007])
	aWire = Part.Wire(aShape.Edges)
	subFace = Part.Face(aWire)
	subFace.check()
	return subFace

def face_rccar_faceWheel_Fa0():
	FC000 = ctr_face_rccar_faceWheel_Fa0_Ctr0()
	rOneFace = FC000
	rOneFace.check()
	return rOneFace

def rccar_faceWheel():
	FA000 = face_rccar_faceWheel_Fa0()
	rOneFig = FA000
	rOneFig.check()
	return rOneFig

def fex_subpax_rccar_platformMain():
	FIG = rccar_facePlatform()
	VEX = FIG.extrude(App.Vector(0, 0, 1250))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 0.0000))
	return VFP
subpax_rccar_platformMain = fex_subpax_rccar_platformMain()

def fex_subpax_rccar_PFfixation0():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 70.0000))
	return VFP
subpax_rccar_PFfixation0 = fex_subpax_rccar_PFfixation0()

def fex_subpax_rccar_PFfixation1():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 110.0000))
	return VFP
subpax_rccar_PFfixation1 = fex_subpax_rccar_PFfixation1()

def fex_subpax_rccar_PFfixation2():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 200.0000))
	return VFP
subpax_rccar_PFfixation2 = fex_subpax_rccar_PFfixation2()

def fex_subpax_rccar_PFfixation3():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 240.0000))
	return VFP
subpax_rccar_PFfixation3 = fex_subpax_rccar_PFfixation3()

def fex_subpax_rccar_PFfixation4():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 380.0000))
	return VFP
subpax_rccar_PFfixation4 = fex_subpax_rccar_PFfixation4()

def fex_subpax_rccar_PFfixation5():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 420.0000))
	return VFP
subpax_rccar_PFfixation5 = fex_subpax_rccar_PFfixation5()

def fex_subpax_rccar_PFfixation6():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 510.0000))
	return VFP
subpax_rccar_PFfixation6 = fex_subpax_rccar_PFfixation6()

def fex_subpax_rccar_PFfixation7():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 550.0000))
	return VFP
subpax_rccar_PFfixation7 = fex_subpax_rccar_PFfixation7()

def fex_subpax_rccar_PFfixation8():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 690.0000))
	return VFP
subpax_rccar_PFfixation8 = fex_subpax_rccar_PFfixation8()

def fex_subpax_rccar_PFfixation9():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 730.0000))
	return VFP
subpax_rccar_PFfixation9 = fex_subpax_rccar_PFfixation9()

def fex_subpax_rccar_PFfixation10():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 820.0000))
	return VFP
subpax_rccar_PFfixation10 = fex_subpax_rccar_PFfixation10()

def fex_subpax_rccar_PFfixation11():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 860.0000))
	return VFP
subpax_rccar_PFfixation11 = fex_subpax_rccar_PFfixation11()

def fex_subpax_rccar_PFfixation12():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1000.0000))
	return VFP
subpax_rccar_PFfixation12 = fex_subpax_rccar_PFfixation12()

def fex_subpax_rccar_PFfixation13():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1040.0000))
	return VFP
subpax_rccar_PFfixation13 = fex_subpax_rccar_PFfixation13()

def fex_subpax_rccar_PFfixation14():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1130.0000))
	return VFP
subpax_rccar_PFfixation14 = fex_subpax_rccar_PFfixation14()

def fex_subpax_rccar_PFfixation15():
	FIG = rccar_facePFfixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1170.0000))
	return VFP
subpax_rccar_PFfixation15 = fex_subpax_rccar_PFfixation15()

def fex_subpax_rccar_platformTriangle2():
	FIG = rccar_faceTriangle()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 310.0000))
	return VFP
subpax_rccar_platformTriangle2 = fex_subpax_rccar_platformTriangle2()

def fex_subpax_rccar_platformTriangle3():
	FIG = rccar_faceTriangle()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 620.0000))
	return VFP
subpax_rccar_platformTriangle3 = fex_subpax_rccar_platformTriangle3()

def fex_subpax_rccar_platformTriangle4():
	FIG = rccar_faceTriangle()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 930.0000))
	return VFP
subpax_rccar_platformTriangle4 = fex_subpax_rccar_platformTriangle4()

def fex_subpax_rccar_bones0():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 90.0000))
	return VFP
subpax_rccar_bones0 = fex_subpax_rccar_bones0()

def fex_subpax_rccar_bones1():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 220.0000))
	return VFP
subpax_rccar_bones1 = fex_subpax_rccar_bones1()

def fex_subpax_rccar_bones2():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 400.0000))
	return VFP
subpax_rccar_bones2 = fex_subpax_rccar_bones2()

def fex_subpax_rccar_bones3():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 530.0000))
	return VFP
subpax_rccar_bones3 = fex_subpax_rccar_bones3()

def fex_subpax_rccar_bones4():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 710.0000))
	return VFP
subpax_rccar_bones4 = fex_subpax_rccar_bones4()

def fex_subpax_rccar_bones5():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 840.0000))
	return VFP
subpax_rccar_bones5 = fex_subpax_rccar_bones5()

def fex_subpax_rccar_bones6():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1020.0000))
	return VFP
subpax_rccar_bones6 = fex_subpax_rccar_bones6()

def fex_subpax_rccar_bones7():
	FIG = rccar_faceBones()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1150.0000))
	return VFP
subpax_rccar_bones7 = fex_subpax_rccar_bones7()

def fex_subpax_rccar_handFixation0():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 70.0000))
	return VFP
subpax_rccar_handFixation0 = fex_subpax_rccar_handFixation0()

def fex_subpax_rccar_handFixation1():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 110.0000))
	return VFP
subpax_rccar_handFixation1 = fex_subpax_rccar_handFixation1()

def fex_subpax_rccar_handFixation2():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 200.0000))
	return VFP
subpax_rccar_handFixation2 = fex_subpax_rccar_handFixation2()

def fex_subpax_rccar_handFixation3():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 240.0000))
	return VFP
subpax_rccar_handFixation3 = fex_subpax_rccar_handFixation3()

def fex_subpax_rccar_handFixation4():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 380.0000))
	return VFP
subpax_rccar_handFixation4 = fex_subpax_rccar_handFixation4()

def fex_subpax_rccar_handFixation5():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 420.0000))
	return VFP
subpax_rccar_handFixation5 = fex_subpax_rccar_handFixation5()

def fex_subpax_rccar_handFixation6():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 510.0000))
	return VFP
subpax_rccar_handFixation6 = fex_subpax_rccar_handFixation6()

def fex_subpax_rccar_handFixation7():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 550.0000))
	return VFP
subpax_rccar_handFixation7 = fex_subpax_rccar_handFixation7()

def fex_subpax_rccar_handFixation8():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 690.0000))
	return VFP
subpax_rccar_handFixation8 = fex_subpax_rccar_handFixation8()

def fex_subpax_rccar_handFixation9():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 730.0000))
	return VFP
subpax_rccar_handFixation9 = fex_subpax_rccar_handFixation9()

def fex_subpax_rccar_handFixation10():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 820.0000))
	return VFP
subpax_rccar_handFixation10 = fex_subpax_rccar_handFixation10()

def fex_subpax_rccar_handFixation11():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 860.0000))
	return VFP
subpax_rccar_handFixation11 = fex_subpax_rccar_handFixation11()

def fex_subpax_rccar_handFixation12():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1000.0000))
	return VFP
subpax_rccar_handFixation12 = fex_subpax_rccar_handFixation12()

def fex_subpax_rccar_handFixation13():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1040.0000))
	return VFP
subpax_rccar_handFixation13 = fex_subpax_rccar_handFixation13()

def fex_subpax_rccar_handFixation14():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1130.0000))
	return VFP
subpax_rccar_handFixation14 = fex_subpax_rccar_handFixation14()

def fex_subpax_rccar_handFixation15():
	FIG = rccar_faceHandFixation()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 0.0000, 1170.0000))
	return VFP
subpax_rccar_handFixation15 = fex_subpax_rccar_handFixation15()

def fex_subpax_rccar_handPlateR1():
	FIG = rccar_faceHandPlateR()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -86.4181, 0.0000))
	return VFP
subpax_rccar_handPlateR1 = fex_subpax_rccar_handPlateR1()

def fex_subpax_rccar_handPlateR2():
	FIG = rccar_faceHandPlateR()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 63.5819, 0.0000))
	return VFP
subpax_rccar_handPlateR2 = fex_subpax_rccar_handPlateR2()

def fex_subpax_rccar_handPlateL1():
	FIG = rccar_faceHandPlateL()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, -86.4181, 0.0000))
	return VFP
subpax_rccar_handPlateL1 = fex_subpax_rccar_handPlateL1()

def fex_subpax_rccar_handPlateL2():
	FIG = rccar_faceHandPlateL()
	VEX = FIG.extrude(App.Vector(0, 0, 10))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 63.5819, 0.0000))
	return VFP
subpax_rccar_handPlateL2 = fex_subpax_rccar_handPlateL2()

def fex_subpax_rccar_handBackR():
	FIG = rccar_faceHandBackR()
	VEX = FIG.extrude(App.Vector(0, 0, 160))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 63.5819, 0.0000))
	return VFP
subpax_rccar_handBackR = fex_subpax_rccar_handBackR()

def fex_subpax_rccar_handBackL():
	FIG = rccar_faceHandBackL()
	VEX = FIG.extrude(App.Vector(0, 0, 160))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 63.5819, 0.0000))
	return VFP
subpax_rccar_handBackL = fex_subpax_rccar_handBackL()

def fex_subpax_rccar_motorBulkR():
	FIG = rccar_faceMotorBulkR()
	VEX = FIG.extrude(App.Vector(0, 0, 120))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 43.5819, 0.0000))
	return VFP
subpax_rccar_motorBulkR = fex_subpax_rccar_motorBulkR()

def fex_subpax_rccar_motorBulkL():
	FIG = rccar_faceMotorBulkL()
	VEX = FIG.extrude(App.Vector(0, 0, 120))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 0.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(0.0000, 43.5819, 0.0000))
	return VFP
subpax_rccar_motorBulkL = fex_subpax_rccar_motorBulkL()

def fex_subpax_rccar_mFoot00():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 160.0000))
	return VFP
subpax_rccar_mFoot00 = fex_subpax_rccar_mFoot00()

def fex_subpax_rccar_mFoot01():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 160.0000))
	return VFP
subpax_rccar_mFoot01 = fex_subpax_rccar_mFoot01()

def fex_subpax_rccar_mFoot02():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 470.0000))
	return VFP
subpax_rccar_mFoot02 = fex_subpax_rccar_mFoot02()

def fex_subpax_rccar_mFoot03():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 470.0000))
	return VFP
subpax_rccar_mFoot03 = fex_subpax_rccar_mFoot03()

def fex_subpax_rccar_mFoot04():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 780.0000))
	return VFP
subpax_rccar_mFoot04 = fex_subpax_rccar_mFoot04()

def fex_subpax_rccar_mFoot05():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 780.0000))
	return VFP
subpax_rccar_mFoot05 = fex_subpax_rccar_mFoot05()

def fex_subpax_rccar_mFoot06():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 1090.0000))
	return VFP
subpax_rccar_mFoot06 = fex_subpax_rccar_mFoot06()

def fex_subpax_rccar_mFoot07():
	FIG = rccar_faceMFoot()
	VEX = FIG.extrude(App.Vector(0, 0, 40))
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 1090.0000))
	return VFP
subpax_rccar_mFoot07 = fex_subpax_rccar_mFoot07()

def fex_subpax_rccar_wheel00():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 160.0000))
	return VFP
subpax_rccar_wheel00 = fex_subpax_rccar_wheel00()

def fex_subpax_rccar_wheel01():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 160.0000))
	return VFP
subpax_rccar_wheel01 = fex_subpax_rccar_wheel01()

def fex_subpax_rccar_wheel02():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 470.0000))
	return VFP
subpax_rccar_wheel02 = fex_subpax_rccar_wheel02()

def fex_subpax_rccar_wheel03():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 470.0000))
	return VFP
subpax_rccar_wheel03 = fex_subpax_rccar_wheel03()

def fex_subpax_rccar_wheel04():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 780.0000))
	return VFP
subpax_rccar_wheel04 = fex_subpax_rccar_wheel04()

def fex_subpax_rccar_wheel05():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 780.0000))
	return VFP
subpax_rccar_wheel05 = fex_subpax_rccar_wheel05()

def fex_subpax_rccar_wheel06():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(434.9067, -196.4181, 1090.0000))
	return VFP
subpax_rccar_wheel06 = fex_subpax_rccar_wheel06()

def fex_subpax_rccar_wheel07():
	FIG = rccar_faceWheel()
	VEX = FIG.revolve(App.Vector(0, 0, 0), App.Vector(0, 1, 0), 360).rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 90)
	VR1 = VEX.rotate(App.Vector(0, 0, 0), App.Vector(1, 0, 0), 0.0000)
	VR2 = VR1.rotate(App.Vector(0, 0, 0), App.Vector(0, 1, 0), -90.0000)
	VR3 = VR2.rotate(App.Vector(0, 0, 0), App.Vector(0, 0, 1), 0.0000)
	VFP = VR3.translate(App.Vector(-434.9067, -196.4181, 1090.0000))
	return VFP
subpax_rccar_wheel07 = fex_subpax_rccar_wheel07()

def fvol_pax_rccar():
	V000 = subpax_rccar_PFfixation0
	V001 = V000.fuse(subpax_rccar_PFfixation1)
	V002 = V001.fuse(subpax_rccar_PFfixation2)
	V003 = V002.fuse(subpax_rccar_PFfixation3)
	V004 = V003.fuse(subpax_rccar_PFfixation4)
	V005 = V004.fuse(subpax_rccar_PFfixation5)
	V006 = V005.fuse(subpax_rccar_PFfixation6)
	V007 = V006.fuse(subpax_rccar_PFfixation7)
	V008 = V007.fuse(subpax_rccar_PFfixation8)
	V009 = V008.fuse(subpax_rccar_PFfixation9)
	V010 = V009.fuse(subpax_rccar_PFfixation10)
	V011 = V010.fuse(subpax_rccar_PFfixation11)
	V012 = V011.fuse(subpax_rccar_PFfixation12)
	V013 = V012.fuse(subpax_rccar_PFfixation13)
	V014 = V013.fuse(subpax_rccar_PFfixation14)
	V015 = V014.fuse(subpax_rccar_PFfixation15)
	V016 = V015.fuse(subpax_rccar_platformMain)
	V017 = V016.fuse(subpax_rccar_platformTriangle2)
	V018 = V017.fuse(subpax_rccar_platformTriangle3)
	V019 = V018.fuse(subpax_rccar_platformTriangle4)
	VFC = V019.removeSplitter()
	return VFC
pax_rccar = fvol_pax_rccar()


pax_rccar.check()
#pax_rccar.exportBrep(f"{outFileName}.brep")
#pax_rccar.exportIges(f"{outFileName}.igs")
#pax_rccar.exportStep(f"{outFileName}.stp")
pax_rccar.exportStl(f"{outFileName}.stl")

